### PR TITLE
Format all files

### PR DESCRIPTION
**Pull request by eginwong**
Hi @Geremia,

I tried to manually diff out the changes between the pre-TidyHtml code and the post, and it was a headache. In this PR, I have run `npx prettier --write .` to consistently format all of the files in a uniform manner. This way, I will be able to better diff between the two data sets.

Hopefully that's okay. If we are concerned with consistency, I can easily add a git webhook via `npm` and `husky` to auto-run the formatter on every commit. Otherwise, I was thinking of running it this one time and that should be it.

After this PR is merged, the diffing process should be much more reasonable and I can return to fixing the missing footnotes. 

FYI: if we merge the previous PR of a mishmash of typos, I can rebase onto the latest master so you can see only the list of diffs for the formatting. There should be no semantic change, only where linebreaks are etc.

### CODE REVIEW

**Comment by Geremia** [comment]
@eginwong The word wrap seems to be something very small. Is there a way to make it not wrapped?

**Comment by eginwong** [comment]
Hi @Geremia. Did you have an example where the word wrap is very small? `Prettier` has a configuration that we can adjust to make the line lengths a bit more reasonable.

Nothing wrong with HTML Tidy, but the files that we are working with were inconsistently formatted and hard to compare easily. With this change, the diffs should be much easier to spot and adjust.

**Comment by Geremia** [comment]
@eginwong One of the files I looked at was DeRegno.htm. I looked at some others, and they all had very narrow fill column widths; all those newlines are unnecessary.

**Comment by eginwong** [comment]
I see what you mean.

I think this is a symptom of an underlying problem. The original files had
a bunch of <td> tags that were unclosed. That causes an unnecessary amount
of nesting. It doesn't affect the html output but it does make parsing and
comparing more difficult.

I plan to go through each file or use a regex match to fix that, so you'll
see the line length at a much more reasonable amount and the nesting
reduced.

**Comment by Geremia** [comment]
@eginwong 
>a bunch of <td> tags that were unclosed

That's permissible in the HTML5 standard. [HTML Tidy](https://www.html-tidy.org/) knows this.

**Comment by eginwong** [comment]
I am not challenging that HTML Tidy is the cause of the problem.

I see where the misunderstanding is. Are you trying to ascertain the reason
why HTMLTidy incorrectly removed the anchor tags?

I haven't yet completed my investigation. I only found that formatting the
files made them easier to work with, not that they fixed any inherent
problems.

When I get some time, I can share some examples of where Tidy incorrectly
removed the anchor tags and we can hypothesize about why.

**Comment by Geremia** [comment]
@eginwong 

Some human error in the HTML probably resulted in HTML Tidy stripping some of the anchors. I think it was that there were multiple anchors with the same name.

**Comment by Geremia** [comment]
@eginwong Perhaps you could add the missing anchors by hand, with a regex?

**Comment by eginwong** [comment]
I am currently adding them by hand. It's a bit of a chore but it's going.

**Pull request merged**
