### PR TITLE
Feature/footnotes

### PR DESCRIPTION
**Pull request by eginwong**
Hello! I can't seem to find the commit that was merged last so I cannot rebase my current branch onto the formatting changes.

This PR fixes up all the files to have closing tags + the formatting.

After that, I plan to fix the footnotes. Sorry for the delay, lots of fixes to address the missing HTML elements.

Regexes used:

`(</td>\n\s+</tr>)\n\s+</td>\n\s+</tr>`
$1

`([A-Za-z:,”.-;’'!—#\]\)"]|</a>|</a[\n\s]+>|<br />|\n\s+>|</table>|blockquote\n\s+>|blockquote>|i\n\s+>|i>|b\n\s+>|b>|</b>|font\n\s+>|font>|</ul>|</h\d>|</ol>|</script>|</ol>|</span>|</span\n\s+>|</center>|\?|<hr />|</dl>)\n\s+(<tr)`

$1</td></tr>$2

`([A-Za-z:,”.-;’'!—#\]\)"]|</a>|</a[\n\s]+>|<br />|\n\s+>|</table>|blockquote\n\s+>|blockquote>|i\n\s+>|i>|b\n\s+>|b>|</b>|font\n\s+>|font>|</ul>|</h\d>|</ol>|</script>|</ol>|</span>|</span\n\s+>|</center>|\?|<hr />|</dl>)\n\s+(<td)`
$1</td>$2

`(</p>\n\s+</td>)\n\s+</p>\n\s+</td>`
$1

`</p>\n\s+</td>\n\s+</td>\n\s+</tr>`

`</p>\n\s+</td>\n\s+</tr>`

### CODE REVIEW

**Comment by eginwong** [comment]
@Geremia This is ready for you to review!

**Comment by Geremia** [comment]
> This PR fixes up all the files to have closing tags

That's not a problem. [HTML Tidy](https://www.html-tidy.org/) made sure it abides by HTML5 standards.

I see you lowercased `<!DOCTYPE html>` to `<!DOCTYPE html>`. Why?

>  + the formatting.

Please submit separate requests for each of your changes.

**Comment by eginwong** [comment]
Yes, I can revert those changes for the doctype. That was the automatic
prettier formatter.

For the separate requests, do you want it per file, per group? I figured
since I ran a whole formatter, I wanted to fix everything up in the same
manner.

Whatever is easiest for you.

**Comment by eginwong** [comment]
Thought about it more. There are no changes to the content, only to layout
(e.g., closing previously unclosed tags). In certain cases (SSJob.htm), the
page was kind of broken before already and these changes fix them to at
least a formattable state. I understand it is a lot of changes to review at
once, but they're all largely the result of the regexes I included in the
PR description.

With respect to the missing anchors that was the original ask, it's not as
simple as using a regex because the pattern is not easily discernible.
Being able to have a consistent format makes diffing between the old and
new versions after HTMLTidy much easier.

**Pull request closed without merging**
