### PR TITLE
refactor: typos and html formatting

### PR DESCRIPTION
**Pull request by eginwong**
I can split into two PRs if there's too much at once. If you'd like, you can review by commit. The last commit has the bulk html style changes.

### CODE REVIEW

**Comment by eginwong** [comment]
@Geremia when you have time to review.

**Comment by Geremia** [comment]
I'll look at this.
I also know there's an issue where certain documents lack anchors. If you'd like, could you please look into fixing that, too (maybe in another PR)? Thanks.

**Comment by Geremia** [comment]
@eginwong You should be able to diff the newer and older versions and find what HTML `<a href>` anchors dropped out when I ran `tidy` (tag: [tidied_HTML](https://github.com/Geremia/AquinasOperaOmnia/releases/tag/tidied_HTML)).

**Comment by eginwong** [comment]
Hey @Geremia. I did a cursory look and diffed between a handful of files from pre and post `tidy` run. I don't see anything obviously wrong.

Could you find an example of one where the `<a href>` anchor dropped for me to analyze? Otherwise, I could probably do a grep on all the files pre and post and do a count to see if any of the files changed.

Thoughts?

**Comment by eginwong** [comment]
Here's what I have so far.

I'll do some digging in a few days to find out what the deltas are.

| Title                                | Pre | Post |
|--------------------------------------|-----|------|
| summa/FS/FS101.html                  | 37  | 27   |
| summa/FS/FS102.html                  | 146 | 143  |
| summa/FP/FP001.html                  | 125 | 124  |
| english/defaultNat.htm               | 13  | 14   |
| english/SermEmitte.htm               | 230 | 263  |
| english/Sent1d3q1a1.htm              | 1   | 2    |
| english/Sent1d8q4a1.htm              | 1   | 2    |
| english/Sent2d43q1a2.htm             | 1   | 2    |
| english/Sent2d43q1a3.htm             | 1   | 2    |
| english/Sent2d43q1a4.htm             | 1   | 2    |
| english/Sent2d43q1a5.htm             | 1   | 2    |
| english/Sent2d43q1a6.htm             | 1   | 2    |
| english/Sent2d43q1proemium.htm       | 1   | 2    |
| english/Sent4d15q3a1.htm             | 1   | 2    |
| english/Sent4d15q3a2.htm             | 1   | 2    |
| english/Sent4d15q3a3.htm             | 1   | 2    |
| english/Sent4d15q3a4.htm             | 1   | 2    |
| english/Sent4d8q1a1.htm              | 1   | 40   |
| english/Sent4d8q1a2.htm              | 1   | 10   |
| english/Sent4d8q1a3.htm              | 1   | 12   |
| english/Sent4d8q1a4.htm              | 1   | 4    |
| english/QDquodlib.htm                | 44  | 47   |
| english/QDdeUnione.htm               | 4   | 5    |
| english/QDdeUnione2.htm              | 0   | 1    |
| english/QDdeUnione3.htm              | 0   | 1    |
| english/QDdeUnione4.htm              | 0   | 1    |
| english/PsalmsAquinas/ThoPs7.htm     | 1   | 2    |
| english/PsalmsAquinas/ThoPs8.htm     | 1   | 2    |
| english/PsalmsAquinas/ThoPs51H52.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs52H53.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs53H54.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs54H55.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs3.htm     | 1   | 2    |
| english/PsalmsAquinas/ThoPs33H34.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs34H35.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs35H36.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs42H43.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs46H47.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs47H48.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs48H49.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs49H50.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs29H30.htm | 1   | 20   |
| english/PsalmsAquinas/ThoPs2.htm     | 1   | 2    |
| english/PsalmsAquinas/ThoPs20H21.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs21H22.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs22H23.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs23H24.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs26H27.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs0.htm     | 1   | 2    |
| english/PsalmsAquinas/ThoPs1.htm     | 1   | 2    |
| english/PsalmsAquinas/ThoPs10H11.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs11H12.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs12H13.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs13H14.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs14H15.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs16H17.htm | 1   | 2    |
| english/PsalmsAquinas/ThoPs17H18.htm | 1   | 2    |
| english/Physics.htm                  | 120 | 119  |
| english/John9.htm                    | 63  | 72   |
| english/John10.htm                   | 73  | 80   |
| english/John11.htm                   | 76  | 84   |
| english/John12.htm                   | 84  | 92   |
| english/John13.htm                   | 88  | 102  |
| english/John14.htm                   | 96  | 112  |
| english/John15.htm                   | 51  | 56   |
| english/John16.htm                   | 67  | 78   |
| english/John17.htm                   | 63  | 72   |
| english/John18.htm                   | 42  | 52   |
| english/John19.htm                   | 37  | 40   |
| english/John20.htm                   | 65  | 72   |
| english/John21.htm                   | 61  | 70   |
| english/DeEternitateMundi.htm        | 0   | 23   |
| english/CorpusChristi.htm            | 29  | 18   |
| english/ContraGentilesND.htm         | 342 | 388  |
| english/ContraImpugnantes.htm        | 31  | 30   |
| Serm11Emitte.htm                     | 230 | 263  |
| Sent4d8q1a1.htm                      | 2   | 40   |
| Sent4d8q1a2.htm                      | 2   | 10   |
| Sent4d8q1a3.htm                      | 2   | 12   |
| Sent4d8q1a4.htm                      | 2   | 4    |
| SensuSensato.htm                     | 202 | 165  |
| SSMatthew.htm                        | 33  | 30   |
| PsalmsAquinas/ThoPs29H30.htm         | 2   | 20   |
| PeriHermeneias.htm                   | 38  | 32   |
| GenCorrup.htm                        | 38  | 43   |
| Eph1.htm                             | 81  | 45   |
| Eph2.htm                             | 63  | 35   |
| Eph3.htm                             | 69  | 38   |
| Eph4.htm                             | 57  | 31   |
| Eph5.htm                             | 17  | 9    |
| Eph6.htm                             | 19  | 10   |
| DeAnima.htm                          | 113 | 112  |
| DeEternitateMundi.htm                | 20  | 22   |
| CorpusChristi.htm                    | 41  | 21   |
| ContraImpugnantes.htm                | 31  | 30   |

**Comment by eginwong** [comment]
Ah, so there used to be wordpress footnotes that are no longer working now. That explains what's happening in `Eph6.htm`. I figure that's where the drop in anchor tags are. Also, the Eph6.htm does not have a corresponding `english/` file so the links are dead on the English page of that source. Something to fix for later. If you're good with me restoring these footnotes, I can do that and submit a separate PR. Let me know!

image

**Comment by Geremia** [comment]
@eginwong Yes, please submit a PR for this. Thank you! 🙏

**Pull request merged**
